"""Add captions_path column to song table

Revision ID: 7356635b7677
Revises: 8924d6abc1d1
Create Date: 2023-07-03 15:38:19.936582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7356635b7677'
down_revision = '8924d6abc1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captions_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('captions_path')

    # ### end Alembic commands ###
