"""Add audio_path column to song table

Revision ID: 8924d6abc1d1
Revises: 
Create Date: 2023-06-29 23:08:07.692199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8924d6abc1d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_path', sa.String(length=255), nullable=False))
        batch_op.drop_column('audio_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('audio_path')

    # ### end Alembic commands ###
